### ISSUE TITLE
Some minor issues in the program

### ISSUE THREAD

**Issue by bbrookie** [Mahmoud-Selim/Speaker-Diarization#1]
First of all thank you very much for open source your program！
when i run the _inference.py_, i found some problem：
1.On line 196 of this file , _wave_ should change to _audio_path_
2.When I want to get split records in other_support, i found there are no records in the txt file, and I tried to add a part of the code like the part of kaldi_comparision：
`if(other_support):
            speakers_str = ""
            start_t = times[0][0]
            end_t   = times[0][1]
            out_path = os.path.join("output", os.path.basename(audio_path)[:-4]+".txt")
            for i in range(1, len(times), 1):
                
                if (times[i][0] - times[i - 1][1] <= 0.03 and labels[i] == labels[i - 1]): 
                    end_t = times[i][1]
                    
                    if(i == len(times) - 1):
                        start_str = time.strftime('%H:%M:%S', time.gmtime(start_t))
                        start_str += ".{}".format(str(int(str(start_t).split('.')[1])%100)) if str(start_t).find('.') > 0 else '.00'
                        end_str = time.strftime('%H:%M:%S', time.gmtime(end_t))
                        end_str += ".{}".format(str(int(str(end_t).split('.')[1])%100)) if str(end_t).find('.') > 0 else '.00'
                        speakers_str += str(labels[i - 1]) + ",{start},{end}".format(start = start_str, end = end_str) + "\n"
                else:
                        start_str = time.strftime('%H:%M:%S', time.gmtime(start_t))
                        start_str += ".{}".format(str(int(str(start_t).split('.')[1])%100)) if str(start_t).find('.') > 0 else '.00'
                        end_str = time.strftime('%H:%M:%S', time.gmtime(end_t))
                        end_str += ".{}".format(str(int(str(end_t).split('.')[1])%100)) if str(end_t).find('.') > 0 else '.00'
                        speakers_str += str(labels[i - 1]) + ",{start},{end}".format(start = start_str, end = end_str)+ "\n"

                        start_t = times[i][0]
                        end_t = times[i][1]`
    
 After modifying this part, there are records in the txt file, but the output of the two formats does not match exactly. Can you help me explain? If the part I modified is incorrect, how can I modify it?
a part of result like this(for ksldi , i change style to [start_t, end_t]):
0,00:00:00.12,00:00:01.98
1,00:00:01.2,00:00:02.4
0,00:00:01.92,00:00:02.96
1,00:00:03.44,00:00:05.99
0,00:00:05.24,00:00:05.72
SPEAKER audio 0  0.12 1.32 <NA> <NA> 0 <NA> <NA>
SPEAKER audio 0  1.20 2.04 <NA> <NA> 1 <NA> <NA>
SPEAKER audio 0  1.92 3.00 <NA> <NA> 0 <NA> <NA>
SPEAKER audio 0  3.44 5.36 <NA> <NA> 1 <NA> <NA>
SPEAKER audio 0  5.24 5.72 <NA> <NA> 0 <NA> <NA>

Thank you again for sharing and wish you live a happy life.

**Comment by Mahmoud-Selim** [comment]
Hello,
Yes you're correct. There was a bug there. I fixed it and updated the main. Regarding your question, which two formats do you compare ?

**Comment by bbrookie** [comment]
> Hello,
> Yes you're correct. There was a bug there. I fixed it and updated the main. Regarding your question, which two formats do you compare ?

In your inference file, two types of records are provided. Between the two records and the same wav file, although the same number of audio segments will be generated, but some segments will be slightly different, just like me As shown in the question
record A
0,00:00:00.12,00:00:01.98
1,00:00:01.2,00:00:02.4
0,00:00:01.92,00:00:02.96
1,00:00:03.44,00:00:05.99
0,00:00:05.24,00:00:05.72
record B
SPEAKER audio 0 0.12 1.32 0
SPEAKER audio 0 1.20 2.04 1
SPEAKER audio 0 1.92 3.00 0
SPEAKER audio 0 3.44 5.36 1
SPEAKER audio 0 5.24 5.72 0

**Comment by bbrookie** [comment]
In the _data_preprocess_diarization.py_ file, I added a restriction after the 39th line
`if(len(seg) > 5200):` 
Without this restriction， some error will occur like
```
ValueError: can't extend empty axis 0 using modes other than 'constant' or 'empty'
or
UserWarning: n_fft=512 is too small for input signal of length=214
  n_fft, y.shape[-1]
```
because i found that some segments obtained by webrtcvad will be 0 or very small


thank you for your reply

**Comment by Mahmoud-Selim** [comment]
> > Hello,
> > Yes you're correct. There was a bug there. I fixed it and updated the main. Regarding your question, which two formats do you compare ?
> 
> In your inference file, two types of records are provided. Between the two records and the same wav file, although the same number of audio segments will be generated, but some segments will be slightly different, just like me As shown in the question
> record A
> 0,00:00:00.12,00:00:01.98
> 1,00:00:01.2,00:00:02.4
> 0,00:00:01.92,00:00:02.96
> 1,00:00:03.44,00:00:05.99
> 0,00:00:05.24,00:00:05.72
> record B
> SPEAKER audio 0 0.12 1.32 0
> SPEAKER audio 0 1.20 2.04 1
> SPEAKER audio 0 1.92 3.00 0
> SPEAKER audio 0 3.44 5.36 1
> SPEAKER audio 0 5.24 5.72 0

Yes, you're correct. There was a bug with the ms part of the results. I fixed it and updated main.

For the `data_preprocess_diarization.py`, it's deprecated and will be removed soon. Has this issue happened with you with the original `data_preprocess.py` ?

**Comment by bbrookie** [comment]
> > > Hello,
> > > Yes you're correct. There was a bug there. I fixed it and updated the main. Regarding your question, which two formats do you compare ?
> > 
> > 
> > In your inference file, two types of records are provided. Between the two records and the same wav file, although the same number of audio segments will be generated, but some segments will be slightly different, just like me As shown in the question
> > record A
> > 0,00:00:00.12,00:00:01.98
> > 1,00:00:01.2,00:00:02.4
> > 0,00:00:01.92,00:00:02.96
> > 1,00:00:03.44,00:00:05.99
> > 0,00:00:05.24,00:00:05.72
> > record B
> > SPEAKER audio 0 0.12 1.32 0
> > SPEAKER audio 0 1.20 2.04 1
> > SPEAKER audio 0 1.92 3.00 0
> > SPEAKER audio 0 3.44 5.36 1
> > SPEAKER audio 0 5.24 5.72 0
> 
> Yes, you're correct. There was a bug with the ms part of the results. I fixed it and updated main.
> 
> For the `data_preprocess_diarization.py`, it's deprecated and will be removed soon. Has this issue happened with you with the original `data_preprocess.py` ?

No problem using the original  `data_preprocess.py`,
Thanks again for your contribution 。

**Comment by Mahmoud-Selim** [comment]
Great! Will close this issue now.
Thanks so much
